# Configuration for Symplectic Geometry arXiv Daily
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "YassineAitMohamed"
repo_name: "Symplectic-arXiv-Daily"
show_authors: True
show_links: True
show_badge: False
max_results: 50
publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/symplectic-arxiv-daily.json'
json_gitpage_path: './docs/symplectic-arxiv-daily-web.json'
json_wechat_path: './docs/symplectic-arxiv-daily-wechat.json'
md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search for symplectic geometry
keywords:
    "Symplectic Geometry, Hamiltonian Mechanics, Poisson Structures": 
        filters: [
        "symplectic geometry",
        "symplectic manifold",
        "symplectic structure",
        "symplectic form",
        "symplectic topology",
        "symplectic capacity",
        "symplectic reduction",
        "symplectic quotient",
        "Marsden-Weinstein reduction",
        "Marsden–Weinstein reduction",
        "moment map",
        "momentum map",
        "symplectic action",
        "Hamiltonian action",
        "Hamiltonian mechanics",
        "Hamiltonian system",
        "Hamiltonian flow",
        "Hamiltonian dynamics",
        "Hamiltonian vector field",
        "canonical transformation",
        "Poisson geometry",
        "Poisson manifold",
        "Poisson structure",
        "Poisson bracket",
        "Poisson algebra",
        "Poisson reduction",
        "Dirac structure",
        "Courant algebroid",
        "generalized complex geometry",
        "Lagrangian submanifold",
        "Lagrangian fibration",
        "Lagrangian intersection",
        "Lagrangian Floer homology",
        "coisotropic submanifold",
        "isotropic submanifold",
        "symplectic groupoid",
        "symplectic Lie algebroid",
        "contact geometry",
        "contact manifold",
        "contact structure",
        "contact form",
        "Reeb vector field",
        "contactomorphism",
        "pre-symplectic geometry",
        "pre-symplectic manifold",
        "multisymplectic geometry",
        "multisymplectic structure",
        "Weinstein conjecture",
        "Hofer geometry",
        "symplectic homology",
        "wrapped Floer homology",
        "Fukaya category",
        "mirror symmetry",
        "SYZ conjecture",
        "Gromov-Witten invariant",
        "J-holomorphic curve",
        "pseudoholomorphic curve",
        "Gromov compactness",
        "quantum cohomology",
        "toric variety",
        "toric manifold",
        "Delzant polytope",
        "Duistermaat-Heckman theorem",
        "localization formula",
        "equivariant cohomology",
        "symplectic cutting",
        "symplectic blowing up",
        "symplectic packing",
        "Gromov width",
        "displacement energy",
        "Hofer norm",
        "symplectomorphism",
        "Hamiltonian diffeomorphism",
        "Arnold conjecture",
        "Floer homology",
        "Novikov ring",
        "Maslov index",
        "Conley-Zehnder index",
        "Morse homology",
        "generating function",
        "Legendrian submanifold",
        "Legendrian isotopy",
        "Legendrian knot",
        "contact homology",
        "cylindrical contact homology",
        "embedded contact homology",
        "Reeb dynamics",
        "periodic orbit",
        "closed characteristics",
        "Rabinowitz Floer homology",
        "polyfold theory",
        "Kuranishi structure",
        "virtual fundamental class",
        "moduli space",
        "Teichmüller space",
        "mapping class group",
        "braid group",
        "knot invariant",
        "HOMFLY polynomial",
        "Jones polynomial",
        "Khovanov homology",
        "Heegaard Floer homology",
        "bordered Floer homology",
        "knot Floer homology",
        "instanton Floer homology",
        "monopole Floer homology",
        "Seiberg-Witten theory",
        "Donaldson theory",
        "gauge theory",
        "Yang-Mills theory",
        "Chern-Simons theory",
        "topological field theory",
        "TQFT",
        "Gromov-Hausdorff convergence",
        "geometric measure theory",
        "calibrated geometry",
        "special Lagrangian",
        "minimal surface",
        "mean curvature flow",
        "Ricci flow",
        "geometric analysis",
        "partial differential equation",
        "variational problem",
        "critical point theory",
        "Morse theory",
        "Lusternik-Schnirelmann theory",
        "minimax method",
        "periodic solution",
        "homoclinic orbit",
        "heteroclinic orbit",
        "integrable system",
        "completely integrable",
        "action-angle coordinates",
        "Liouville theorem",
        "Arnold-Liouville theorem",
        "KAM theory",
        "Kolmogorov-Arnold-Moser",
        "perturbation theory",
        "small divisor",
        "resonance",
        "normal form",
        "Birkhoff normal form",
        "Hamiltonian perturbation",
        "adiabatic invariant",
        "geometric mechanics",
        "Lagrangian mechanics",
        "Euler-Lagrange equation",
        "Noether theorem",
        "symmetry reduction",
        "momentum conservation",
        "energy conservation",
        "phase space",
        "configuration space",
        "cotangent bundle",
        "tangent bundle",
        "fiber bundle",
        "principal bundle",
        "vector bundle",
        "characteristic class",
        "Chern class",
        "Euler class",
        "Stiefel-Whitney class",
        "cohomology",
        "de Rham cohomology",
        "sheaf cohomology",
        "Čech cohomology",
        "differential form",
        "closed form",
        "exact form",
        "Poincaré lemma",
        "Stokes theorem",
        "integration",
        "fiber integration",
        "Thom class",
        "Gysin sequence",
        "spectral sequence",
        "Leray-Serre spectral sequence",
        "algebraic topology",
        "homotopy theory",
        "homology theory",
        "K-theory",
        "bordism theory",
        "characteristic number",
        "signature",
        "genus",
        "Pontryagin class",
        "Todd class",
        "Hirzebruch polynomial",
        "Riemann-Roch theorem",
        "Atiyah-Singer index theorem",
        "elliptic operator",
        "Fredholm operator",
        "Sobolev space",
        "functional analysis",
        "operator theory",
        "spectral theory",
        "eigenvalue problem",
        "nodal domain",
        "heat kernel",
        "Green function",
        "fundamental solution"
        ]
