name: Auto Update Tables

on:
  push:
    paths:
      - 'symplectic_geometry_articles.csv'
      - 'generate_tables.py'
      - 'index_template.html'

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # ✅ Donne les permissions d’écriture au bot

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true   # ✅ Active les credentials pour push
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pandas

    - name: Generate index.html
      run: python generate_tables.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add index.html
        git commit -m "Auto-update README and index.html from CSV" || echo "No changes to commit"
        git push
